# ===============================
# Environment & Application Info
# ===============================
spring.profiles.active=dev
spring.application.name=YRHP_REVIEW_GENERATOR

# ===============================
# Database Configuration (Base)
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.29.150:3306/review_generator
spring.datasource.username=review-card
spring.datasource.password=Str0ng!885599
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# ===============================
# File Upload Configuration (Base)
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=/opt/review-card/data
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
max.file.size=2MB

# ===============================
# Static Resources Handling
# ===============================
spring.resources.static-locations=file:///opt/review-card/data/,classpath:/static/
upload.resource.handler=/uploads/**
upload.resource.access.url=/uploads/
upload.resource.location=/opt/review-card/data/

# ===============================
# Security
# ===============================
spring.security.user.password=ENCODED_PASSWORD_HERE

# ===============================
# Logging (Base)
# ===============================
logging.level.org.springframework.security=INFO
logging.level.com.yrhp.crud.service=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
#logging.file.name=logs/application.log

logging.level.org.springframework.web=INFO
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.org.springframework.context=INFO


# ===============================
# Thymeleaf Configuration
# ===============================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ===============================
# OpenAI Configuration
# ===============================
OPEN_AI_URL=https://api.openai.com/v1/chat/completions
OPEN_AI_KEY=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

# For JSON date formatting
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss