# ===============================
# Database Configuration (Dev)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/review_generator
spring.datasource.username=root
spring.datasource.password=Varun@2005
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update


# ===============================
# File Upload Configuration (Dev)
# ===============================
spring.servlet.multipart.location=C:/uploads
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# ===============================
# Static Resources Handling (Dev)
# ===============================
spring.resources.static-locations=file://C:/uploads/,classpath:/static/
upload.resource.handler=/uploads/**
upload.resource.location=C:/uploads/

# ===============================
# Logging (Dev)
# ===============================
logging.level.com.yrhp.crud=INFO
#logging.file.name=C:/log/application-dev.log
logging.level.com.yrhp.crud.service=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR

# ===============================
# OpenAI Configuration
# ===============================
OPEN_AI_KEY=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

# For JSON date formatting
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

logging.level.com.yrhp.crud.service.ClientService=DEBUG
logging.level.org.springframework.transaction=DEBUG

server.forward-headers-strategy=framework

GOOGLE_CLIENT_ID=797242607359-84dkv3cgnid8nodc9h0uucu55vne61or.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
GOOGLE_REDIRECT_URI=http://localhost:8080/user/google/callback
GOOGLE_CLIENT_REDIRECT_URI=http://localhost:8080/client/google/callback
# Production should use: https://review.magicreview.in/client/google/callback

TOKEN_ENCRYPTION_KEY=FqqlvQUg0f9Tefv/Bs6hAYsKOTJu5CPvxU5j6k19E9E=

